### PR TITLE
Add .circleci/config.yml

### PR DESCRIPTION
**Pull request by botterthanyou96**

### CODE REVIEW

**Comment by Illegal-Services** [comment]
@botterthapnyou96 Hi, you wanna me to use workflow on Github and that's why you pull request that? I'm a little confused, maybe you can help me understand the pull request you opened.
Also for further information, Illegal Services currently does have a workflow and pipeline, it's just private and only me can use it.

**Comment by botterthanyou96** [comment]
I apologize greatly didn't mean to upset you if I did I just want do a lil
doxxing pay for access?

**Comment by botterthanyou96** [comment]
Do you have a telegram? Or what's app..I'm willing to pay to play

**Comment by Illegal-Services** [comment]
> Do you have a telegram? Or what's app..I'm willing to pay to play

I have both Discord and Telegram: mathieudummy

**Comment by botterthanyou96** [comment]
I just need your tele or whatever encrypted chat you use to talk freely

**Comment by Illegal-Services** [comment]
I sent you my contact information in my message above.

**Pull request closed without merging**
